// @ts-nocheck

function rootReadmeTemplate(projectName, fullStack) {
    if (fullStack) {
        return `# ${projectName}

Generated by scaffold-mnadalc-project.

## Workspace Structure

- \`client/\`: React + Vite frontend
- \`server/\`: Express backend

Frontend test folders:

- \`client/src/__tests__\` for app-level tests/setup
- \`client/src/components/__tests__\` for component tests
- \`client/src/api/__tests__\` for API/mocks tests
- \`client/src/e2e\` for Playwright

## Root Commands

- \`pnpm dev\`: run client and server in parallel
- \`pnpm build\`: build all packages
- \`pnpm typecheck\`: type-check all packages
- \`pnpm lint\`: lint all packages
- \`pnpm test\`: run client tests
- \`pnpm test:run\`: run client tests once

## Git Hooks

The root pre-commit hook runs:

1. \`pnpm --filter client typecheck\`
2. \`pnpm --filter client exec lint-staged\`
3. \`pnpm --filter server build\`
4. \`pnpm --filter server lint\`
`;
    }
    return `# ${projectName}

Generated by scaffold-mnadalc-project.

## Test Layout

- \`src/__tests__\`: app-level tests and setup
- \`src/components/__tests__\`: component tests
- \`src/api/__tests__\`: API/mocks tests
- \`src/e2e\`: end-to-end tests (Playwright)

## Commands

- \`pnpm dev\`: run Vite dev server
- \`pnpm build\`: production build
- \`pnpm lint\`: lint source
- \`pnpm typecheck\`: TypeScript type check
- \`pnpm test\`: run Vitest in watch mode
- \`pnpm test:run\`: run Vitest once
`;
}
function frontendPreCommit(fullStack) {
    if (fullStack) {
        return `#!/usr/bin/env sh

pnpm --filter client typecheck
pnpm --filter client exec lint-staged
pnpm --filter server build
pnpm --filter server lint
`;
    }
    return `#!/usr/bin/env sh

pnpm typecheck
pnpm exec lint-staged
`;
}


export { frontendPreCommit, rootReadmeTemplate };
