// @ts-nocheck

function frontendReadme(fullStack) {
    if (fullStack) {
        return `# Client

React + Vite frontend generated by scaffold-mnadalc-project.

## Test Layout

- \`src/__tests__\`: app-level tests and setup
- \`src/components/__tests__\`: component tests
- \`src/api/__tests__\`: API/mocks tests
- \`src/e2e\`: end-to-end tests (Playwright)

## Commands

- \`pnpm dev\`: run Vite dev server
- \`pnpm build\`: production build
- \`pnpm lint\`: lint source
- \`pnpm typecheck\`: TypeScript type check
- \`pnpm test\`: run Vitest in watch mode
- \`pnpm test:run\`: run Vitest once
`;
    }
    return `# Application

Generated with scaffold-mnadalc-project.

## Test Layout

- \`src/__tests__\`: app-level tests and setup
- \`src/components/__tests__\`: component tests
- \`src/api/__tests__\`: API/mocks tests
- \`src/e2e\`: end-to-end tests (Playwright)

## Commands

- \`pnpm dev\`: run Vite dev server
- \`pnpm build\`: production build
- \`pnpm lint\`: lint source
- \`pnpm typecheck\`: TypeScript type check
- \`pnpm test\`: run Vitest in watch mode
- \`pnpm test:run\`: run Vitest once
`;
}

export { frontendReadme };
